# Language selection
sudo: true
language: c
# Compiler selection
compiler:
  - clang
  - gcc
install:  ./src/install-deps.sh
script:
  - cd src && make test
secure: "DabEwYVK35ffUXfCsWmbtATLRpo4aWr+YFaGxaKHbxzew1O/+vu/+awKtGWEu8F+a5zz7VevghLeTkSnsOBjhuyPew5F1qmzH2/GaHl43nz68Q3kWOdE4AnXgYENdzxdkXXWcav0/NRApI7zIF74EcQ4JLXK53HnCpuwv45R5OQNuP1wmQ3uyGR+XFli58Aqk1nXC/GDSKlEvmATBRhnLQmDCDKGiNmqAZNK50/IdW5ncc5tLE5iyhGv1tvG9NBKrrK6HxndbxiWtcu3k+ign2unsKNnmsp0drqAZgFFfI1sbZVa+WkEXmKg0lv4LfijI6+w+glSSRt5/4WOShMDJW+zevav/vDGbjaXux3EEq+eQu7E28N87BDx0yt2IRlzu1VBNmvzz3Uimiougk69sRn6hY/oLy8hUOpzOYzNeD6c9wO+CrESZ/Wq42psF4Q1eiKHSw4iSFrLCJwgCTcuXYAIyxCLhF982wJy+9bYPxW54+fKHZJTzUdeo6745njWSR1fNozfNLMWrGG5TDnMMKhIaoHDqf7oG+ABIipjS4UOmL3obq+TyvRsd4nWhKe/hr31gVN+7TV53BoAf5bVoqzqeaA6aAEg7B5U7DYmrI4O3rkqT92MDMwhE9pNcCeBt5DumJADXMV+qM/O6K42sHARnYgyu/iKU0N6Bupb7LQ="
